apiVersion: apps/v1
kind: Deployment
metadata:
  name: peed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peed
  template:
    metadata:
      labels:
        app: peed
    spec:
      containers:
      - image: okteto.dev/peed:latest
        name: peed
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "53c33ba6-620a-4535-9cab-b57648f7d361"
        - name: Vless_Path
          value: "/37d37dud7dd8e8kdisowe9ir8idki"
        - name: Vmess_UUID
          value: "53c33ba6-620a-4535-9cab-b57648f7d361"
        - name: Vmess_Path
          value: "/37d37dud7dd8e8kdisowe9ir8idki"
        - name: Share_Path
          value: "/v2link"
