apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: peed
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "peed"
    port: 8080
  selector:
    app: peed
